name: rcmdcheck and BiocCheck

on: [push, pull_request]

env:
  cache-version: v1

jobs:
  r-build-and-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Query dependencies and update old packages
        run: |
          BiocManager::install(ask=FALSE)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      # This lets us augment with additional dependencies
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt update
          sudo apt install -y valgrind texlive-latex-base
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          
      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          BiocManager::repositories()
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_cran("rcmdcheck")
          BiocManager::install("BiocCheck")
        shell: Rscript {0}

      - name: CheckLinux
        if: runner.os == 'Linux'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(build_args = c("--no-manual", "--no-build-vignettes"), args=c("--use-valgrind"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
        
      - name: BiocCheck
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: | 
          checkres <- BiocCheck::BiocCheck()
          checkres$warning$checkVersionNumber <- NULL
          if (length(checkres$warning) > 0 || length(checkres$error) > 0) error("Failed BiocCheck")
        shell: Rscript {0}
        
      
      




